[fixed] keeping form data on refresh
kffl/triss-client pull request #28
Opened 2020-12-17 04:48 UTC by pietrzakkuba

Linked issues: 

## Description

## Potential TODOS/considerations

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-12-17 11:59 UTC, MateuszTamborski approved these changes
👍👍👍

2020-12-17 15:54 UTC, MarceliJerzynski requested changes
You, as you said "leniwa kurwo", please write requestTemplate or something like that, because we don't want to write few times code that can be implemented once

2020-12-17 23:09 UTC, Rybov approved these changes

2020-12-18 05:59 UTC, MarceliJerzynski approved these changes

2020-12-18 07:44 UTC, merged